# Generated by Django 2.0.6 on 2018-07-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendee', '0002_auto_20180705_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attend_no',
            new_name='receipt_no',
        ),
    ]
